### ISSUE TITLE
Cleanup documentation generation for fletch packages

### ISSUE THREAD

**Issue by ricowind** [dartino/sdk#305]
@karlklose @sgjesse 
I will land a change that makes us archive documentation for our packages.

The documentation will be put into the sdk bundle and be available online.
There is a number of hacks in the current implementation:
  The current implementation is linux only (we only have a forked version for linux on gcs)
  The way the libraries files is used is hackish, Karl et al is working on making that better
  This is currently mixed up with the sdk bundling, we may want to completely separate it
  We should try to convince dartdoc people that one should be able to give dartdoc a set of packages that should be documented, the output should include an overall page with links to the individual packages

**Comment by mit-mit** [comment]
I booked a meeting with a few dartdoc folks to discuss this.

**Comment by mit-mit** [comment]
The docs for packages work fine now. We still need to figure out what to do for core libs. Maybe try to reexport them like we do for packages?

**Comment by mit-mit** [comment]
Closing, @sigurdm fixed this in https://github.com/dartino/sdk/commit/acf9af6231e46e4df34fd7d14a6c1ab0c8d75766
