### ISSUE TITLE
Fletch command usage reports

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#350]

**Comment by lukechurch** [comment]
Suggest that I pick this up, unless you've already started @mit-mit?

**Comment by mit-mit** [comment]
Im doing the approval part, would be great if you could do the
implementation part!

**Comment by mit-mit** [comment]
PDD was completed and is in review.

**Comment by mit-mit** [comment]
Privacy review has been signed off, over to you @lukechurch for implementation!

**Comment by mit-mit** [comment]
Closing this, @danrubel pls confirm that https://github.com/dartino/sdk/issues/492 has all the picks we needed!
