### ISSUE TITLE
Serial support

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#367]

**Comment by mit-mit** [comment]
@sgjesse, can we close this? I believe this is supported?

**Comment by sgjesse** [comment]
Closing this for now. We can open new bug on enhancements.

**Comment by sgjesse** [comment]
Closing this for now. We can open new bug on enhancements.

**Comment by sgjesse** [comment]
Closing this for now. We can open new bug on enhancements.

**Comment by sgjesse** [comment]
Closing this for now. We can open new bug on enhancements.
