### ISSUE TITLE
TCP support

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#368]

**Comment by karlklose** [comment]
- [x] FreeRTOS-Plus-TCP stack included in disco_dartino
- [x] Ethernet driver for LAN8720A chip (the one on the F7 discovery board) and ethernet Dart library
- [x] Basic TCP socket library with host lookup, connect, read, write
- [ ] Server (listening) socket support
- [ ] UDP

**Comment by mit-mit** [comment]
Moved Socket and UDP support to a new tracking bug (#485) as those do not block the completion of the 0.4.0 release.
