### ISSUE TITLE
Fletch build image support

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#373]
Build flashable image from fletch program

**Comment by ricowind** [comment]
Closing this, sgjesse made this possible with the dartino x-build command

**Comment by mit-mit** [comment]
Re-opening, we should not close this until x-build has been promoted to build

**Comment by ricowind** [comment]
Promoted to build?
This is already in the latest dev channel build, but it has not been promoted to users yet if that is what you mean? (if that is what you mean, do you expect us to not close all the bugs we fix until it has shipped to users? - that would suck, since you have no progress indication)

**Comment by mit-mit** [comment]
By promoted, I mean renamed from x-build to build. I thought x- was used
for things that were not completed yet.

**Comment by sgjesse** [comment]
The `x-` prefix is for commands which are still under development/in beta. I don't think we will remove the `x-` prefixes from these commands anytime soon - unless we decide either

- these commands are probably going to stick
- or we don't care about changing the commands between releases

@lukechurch What is your take on this?

**Comment by mit-mit** [comment]
@sgjesse I discussed with @lukechurch, and we agree that this naming would be great:

```
dartino build <file name>: build flashable image containing the Dart code in <file name>

dartino flash <file name>: build flashable image containing the Dart code in <file name>,
   and flash it to a connected STM board
```

Longer term we probably need to add support for flashing pre-built images, and for specifying which device to flash to (e.g., when multiple supported ones are connected), but that can follow later.
