### ISSUE TITLE
The compiler crashes when the source file does not exist

### ISSUE THREAD

**Issue by karlklose** [dartino/sdk#374]
If foo.dart does not exist,
  $ fletch compile file foo.dart
will lead to the following crash. There should be an error message instead.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The null object does not have a method 'findLocal'.

NoSuchMethodError: method not found: 'findLocal'
Receiver: null
Arguments: ["entry"]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      FletchBackend.enqueueHelpers.<anonymous closure> (package:fletchc/src/fletch_backend.dart:322:32)
#3      FletchBackend.loadHelperMethods (package:fletchc/src/fletch_backend.dart:419:35)
#4      FletchBackend.enqueueHelpers (package:fletchc/src/fletch_backend.dart:320:5)
#5      Compiler.compileLoadedLibraries (package:compiler/src/compiler.dart:1001:13)
#6      Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:877:7)
#7      _rootRunUnary (dart:async/zone.dart:914)
#8      _CustomZone.runUnary (dart:async/zone.dart:810)
#9      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#10     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#11     _Future._completeWithValue (dart:async/future_impl.dart:376)
#12     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#13     _rootRun (dart:async/zone.dart:907)
#14     _CustomZone.run (dart:async/zone.dart:802)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:735)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#17     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

**Comment by mit-mit** [comment]
This does not seem to fail anymore, closing as state.

```
mit-macbookpro2:tmp mit$ dartino compile foobar.dart
Using template settings file '/Users/mit/dev/dartino-sdk/internal/.dartino-settings'
foobar.dart:
Error: Error reading 'foobar.dart' (No such file or directory)
```
