### ISSUE TITLE
Pi documentation: Path needed for where the flash command should be run from 

### ISSUE THREAD

**Issue by lukechurch** [dartino/sdk#398]
From latest testing:

re: https://dart-lang.github.io/fletch/index.html

For the section 
```
platforms/raspberry-pi2/flash-sd-card
``` 

It's not obvious where this should be run from, just needs a note that it's in the fletch-sdk folder.

**Comment by mit-mit** [comment]
@lukechurch., that should be implicit at the step right before is:

```
cd $HOME/dartino-sdk/
dartino run samples/general/hello.dart
```

Did you observe someone having issues with this?

**Comment by mit-mit** [comment]
Closing pending further information
