### ISSUE TITLE
Rename dart-dependencies-fletch bucket

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#402]
As part of the fletch->dartino rename we should update the cloud storage bucket we use in DEPS:
```
dart-dependencies-fletch
```

**Comment by sgjesse** [comment]
As far as I can see there is no renaming of Cloud Storage buckets, so we will have to create a new one, copy over the content and (maybe) delete the old one.

**Comment by madsager** [comment]
The SoD repo also pulls from our cloud storage bucket. So, before deleting the old one we need to make sure to fix their DEPS. I'll be happy to do that.

**Comment by ricowind** [comment]
we should never delete that bucket, it will destroy our ability to do old builds

**Comment by ricowind** [comment]
I will create a new bucket for our dependencies, copy the existing used ones over and update the deps

**Comment by mit-mit** [comment]
OK, that sounds great.

**Comment by ricowind** [comment]
done, we now use dartino-dependencies
