### ISSUE TITLE
github sample test is broken

### ISSUE THREAD

**Issue by ricowind** [dartino/sdk#417]
The rename of fletch->dartino broke this, and I did not have enough insight to figure out the test data model.

@skabet @zerny 
Could one of you take a look, I have suppressed the failure in samples/samples.status (diff to 333610f48e958acbf0f594c29afe4b9786d1744d if you want to see changes)

**Comment by zerny** [comment]
I'll take a look at this.

-Ian

**Comment by zerny** [comment]
Fixed by 07a1d057
