### ISSUE TITLE
lcd package: text output at unexpected location

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#427]
If you clear the screen and then render text in a tight loop, the text occasionally is rendered at the wrong location, for example this code:

```
import 'package:stm32f746g_disco/stm32f746g_disco.dart';
import 'package:stm32f746g_disco/lcd.dart';

main() {
  STM32F746GDiscovery discoBoard = new STM32F746GDiscovery();
  var display = discoBoard.frameBuffer;

  while (true) {
    display.clear(Color.black);
    display.writeText(100, 100, 'HHHEEELLLOOOOO');
  }
}
```

**Comment by sigurdm** [comment]
We could try doing the same operations in a tight c-loop.

**Comment by sgjesse** [comment]
The foreign call was missing an argument. The last argument was for alignment, and that was getting a "random" value from the stack.
