### ISSUE TITLE
Unable to attach since 13b9cc52

### ISSUE THREAD

**Issue by zerny** [dartino/sdk#428]
It is no longer possible to attach to a manually started VM since 13b9cc52 (Use batch runner when there's no explicit session.)

Repro:
In terminal 1, run:
```
$ out/DebugIA32/dartino-vm --port=51234
Waiting for compiler on 127.0.0.1:51234
```
In terminal 2, run:
```
$ out/DebugIA32/dartino attach tcp_socket 127.0.0.1:51234
```
The latter should return control to the terminal after attaching, but hangs instead.

**Comment by peter-ahe-google** [comment]
Should work if you use an explicit session. If you don't use a session, we don't use the persistent process.

@sgjesse
