### ISSUE TITLE
Analyzer should rely on a Dart SDK inside the Dartino SDK

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#452]
Currently the Dartino plug-in analyzer relies on a separately installed Dart SDK. This complicated the getting started experience. Given we already have almost a full Dart SDK inside the Dartino SDK, it would be great to just extend that to whatever components we are missing.

**Comment by mit-mit** [comment]
Dan, any news on this one?

**Comment by danrubel** [comment]
A step in this direction... https://codereview.chromium.org/1866823002/
