### ISSUE TITLE
Support 'dartino analyze' action

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#456]
For regular Dart code you can verify it's correctness using the dart analyzer in the command line:

```
mit-macbookpro:samples mit$ dartanalyzer general/hello.dart
Analyzing [general/hello.dart]...
```

It would be nice to have the same thing for dartino, only integrated into our dartino command:
```
mit-macbookpro:samples mit$ dartino analyze general/hello.dart
Analyzing [general/hello.dart]...
```

**Comment by mit-mit** [comment]
Discussed with @lukechurch and he OK'ed using `dartino analyze`

**Comment by eernstg** [comment]
Hej Michael,

der var lige et punkt hvor jeg har en reaktion fra dybt nede i rygraden:
Det er ikke 'verify its correctness' men derimod noget klart mindre, fx
'verify its type correctness' or 'rule out certain kinds of errors' eller
noget i den stil, men der er stadig masser af rum til bugs. ;-)

On Fri, Mar 18, 2016 at 1:14 PM, Michael Thomsen <notifications@github.com>
wrote:

> For regular Dart code you can verify it's correctness using the dart
> analyzer in the command line:
>
> mit-macbookpro:samples mit$ dartanalyzer general/hello.dart
> Analyzing [general/hello.dart]...
>
> It would be nice to have the same thing for dartino, only integrated into
> our dartino command:
>
> mit-macbookpro:samples mit$ dartino analyze general/hello.dart
> Analyzing [general/hello.dart]...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dartino/sdk/issues/456>
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by mit-mit** [comment]
Yup, I was being a little colloqial

**Comment by lukechurch** [comment]
@eernstg say what? :)

**Comment by eernstg** [comment]
Ah, I just quipped that you can have type correct programs with bugs.

On Fri, Mar 18, 2016 at 1:19 PM, Luke Church <notifications@github.com>
wrote:

> @eernstg <https://github.com/eernstg> say what? :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dartino/sdk/issues/456#issuecomment-198327806>
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by lukechurch** [comment]
We should work on fixing that - it seems very doable.

**Comment by eernstg** [comment]
'ts called Coq. ;)

On Fri, Mar 18, 2016 at 1:22 PM, Luke Church <notifications@github.com>
wrote:

> We should work on fixing that - it seems very doable.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dartino/sdk/issues/456#issuecomment-198328307>
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984
