### ISSUE TITLE
Uncaught exception: '[bulkHandleSetIfNull] isn't implemented.'

### ISSUE THREAD

**Issue by jimbeveridge** [dartino/sdk#461]
When I try to run Dartino on this code:
```
s ??= new MyClass();
```

I get this error:
```
Uncaught exception: '[bulkHandleSetIfNull] isn't implemented.'
```

The error message tells the story, but I wondered if there is a timeframe for implementing `??=`? The other null-aware operators, `??` and `?.`, seem to work.

**Comment by sgjesse** [comment]
Sigurd will look into the implementation of `??=`.

**Comment by sigurdm** [comment]
Cl is under review: https://codereview.chromium.org/1843083003/
