### ISSUE TITLE
dartino command line analytics

### ISSUE THREAD

**Issue by danrubel** [dartino/sdk#467]
There are several places in https://codereview.chromium.org/1844053006 where dartino command line analytics should be recorded.

**Comment by danrubel** [comment]
Progress ...
* [analytics in dartino cmdline](https://codereview.chromium.org/1949803003/) with [improves](https://codereview.chromium.org/1967443002/)
* [log requests with hashed paths](https://codereview.chromium.org/1968683002/)

**Comment by mit-mit** [comment]
@danrubel was this completed?

**Comment by danrubel** [comment]
https://codereview.chromium.org/1988343002/
Once this lands, yes.

**Comment by mit-mit** [comment]
OK, lets try to get this into 0.4.1 (scheduled for next week)

**Comment by mit-mit** [comment]
@danrubel looks like that review landed, so we can close this?

**Comment by danrubel** [comment]
Fixed
