### ISSUE TITLE
Update documentation with new stm32 package name

### ISSUE THREAD

**Issue by sgjesse** [dartino/sdk#472]
In https://github.com/dartino/sdk/commit/263803d75637aaf64bd02c2105539d638dbdfa3f the package `stm32f746g_disco` was renamed to `stm32` to have all STM board support in one package. The change did update all the samples, but the documentation probably have references to the old package.

The only change needed will be changing

```
import 'package:stm32f746g_disco/src/stm32f7_constants.dart'
```
to
```
import 'package:stm32/src/constants.dart';
```
The instantiation of the board object is still the same
```
STM32F746GDiscovery disco = new STM32F746GDiscovery();
```

**Comment by mit-mit** [comment]
Fixed in https://github.com/dartino/www.dartino.org/commit/f5910615daf1ad42d94bee8719dd8b05468e53c6
