### ISSUE TITLE
Document how to debug on the device using 'dartino debug'

### ISSUE THREAD

**Issue by sgjesse** [dartino/sdk#480]
Some documentation of how to do command-line debugging on a device with `dartino debug` over the ST-Link serial port.

**Comment by sigurdm** [comment]
As a first step I added some information to the wiki-page: https://github.com/dartino/sdk/wiki/Debugging-via-serial-on-the-STM-Discovery-board.

**Comment by sigurdm** [comment]
And now sent some text to @mit-mit to incorporate on the page when launching 0.4.0
