### ISSUE TITLE
Dartino Atom plugin should configure file tree view to exclude build artifacts

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#488]
After a few flashes the tree view on the right showing files becomes quite cluttered. Would be great if it could be configured to exclude build artifacts, incl.:

*.snapshot
*.bin
*.info.json

**Comment by sgjesse** [comment]
We should also put all build artifacts into a build directory.

The question is how to structure this. E.g.
```
my-project/dartino.yaml
my-project/test1/test.dart
my-project/test2/test.dart
```
Now running (in my-project):
```
dartino build test1/test.dart
dartino build test2/test.dart
```
Should probably create the following
```
my-project/build/test1/test.bin
my-project/build/test1/test.elf
my-project/build/test1/test.snapshot
my-project/build/test1/test.info.json
my-project/build/test2/test.bin
my-project/build/test2/test.elf
my-project/build/test2/test.snapshot
my-project/build/test2/test.info.json
```

**Comment by mit-mit** [comment]
@danrubel what do you think?

**Comment by danrubel** [comment]
I like the idea. Let me see what can be done.

**Comment by mit-mit** [comment]
Tracking the build part in https://github.com/dartino/sdk/issues/513

**Comment by danrubel** [comment]
After digging into this further, this would be a fair amount of work and be counter to the approach of most other Atom plugins. I recommend [putting all build artifacts into a build directory](https://github.com/dartino/sdk/issues/513) and not filter the tree view.

**Comment by mit-mit** [comment]
I'm OK with that suggestion @danrubel. Closing this.
