### ISSUE TITLE
[runtime-gc] We need to test program/process GC very carefully to avoid bugs

### ISSUE THREAD

**Issue by mkustermann** [dartino/sdk#50]
Currently we do not have many tests for GC and in particular not very precise tests.

We need to be able to **test reliably** that our (moving) GCs, namely:
 * process GC
 * program GC
 * program changes (changed classes, methods, statics) GC

correctly handle/update:

* all live processes (and their root sets)
* shared immutable data between processes
* heap/spaces of died (or about to die) processes (see `Process.exit()` functionality)
* messages/process-spaces inside port queues of processes
* ...

**Comment by mit-mit** [comment]
@ErikCorryGoogle is this bug still relevant with the new GC impl.?
