### ISSUE TITLE
0.5 documentation updates

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#505]
- [x] Add debugger details https://dartino.org/tool.html
  - https://codereview.chromium.org/2119873002/
- [x] Add more details about Atom
  - https://codereview.chromium.org/2119873002/
- [x] Update getting started with more samples
  - https://codereview.chromium.org/2119873002/
- [x] Add page talking about concurrency (fibers and processes)
  - https://codereview.chromium.org/2124493002/
  - https://codereview.chromium.org/2124473002/
- [x] Add F411 board
  - https://codereview.chromium.org/2125443002/

**Comment by mit-mit** [comment]
All changes landed. Will do the push (i.e., `firebase deploy`) once the SDK goes out.

**Comment by sgjesse** [comment]
0.5.0 has been released (0.5.0-dev.1.5).
