### ISSUE TITLE
Atom Debugger UI

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#515]
Atom Debugger UI supporting breakpoints, variables inspection, and call stack

**Comment by sigurdm** [comment]
Work in progress for the dartino side of this is on: https://codereview.chromium.org/1987673002. Development happens in lock-step with the Atom plugin.

**Comment by sigurdm** [comment]
Breakpoint support and listing of call stack is landed.
Variables inspection is out for review: https://codereview.chromium.org/2060283002/

**Comment by sigurdm** [comment]
Variables inspection is landed.

**Comment by mit-mit** [comment]
Very nice, will test this soon!
