### ISSUE TITLE
API docs missing for Dartino libraries

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#516]
The Dartino API docs (https://dartino.github.io/api/) currently have generated docs for Dartino packages (e.g., [package FFI](https://dartino.github.io/api/ffi/ffi-library.html)) however docs are missing for Dartino libraries (e.g. [library FFI](https://github.com/dartino/sdk/blob/master/lib/ffi/ffi.dart)).

The current method of generating them in the bundle_script fails with analyzer issues. We need to figure out how to resolve that, or come up with an alternate approach.

**Comment by sgjesse** [comment]
Sigurd will take a look.

**Comment by sigurdm** [comment]
https://codereview.chromium.org/2108613002/ is up for review.
