### ISSUE TITLE
Debugger does not recover from failed connection

### ISSUE THREAD

**Issue by sgjesse** [dartino/sdk#526]
If a failing connection is made to a VM waiting for a debugger connection - like in #525, and then a new connection is attempted the VM hits an ASSERT:

```
../../src/vm/session.cc:85: error: Unexpected message opcode 0 received in state Connected, live-editing: false, debugging: true>
```

**Comment by sigurdm** [comment]
This is fixed by https://github.com/dartino/sdk/commit/38d4ccb97dc05d8cb244643ea07a665f7bbc0e51
