### ISSUE TITLE
Improve error handling of "late errors" in test.dart

### ISSUE THREAD

**Issue by peter-ahe-google** [dartino/sdk#53]
See https://codereview.chromium.org/1194913003/#msg7

We should probably:

* Add EventListener.lateError, and
* Add a new status DelayedAsyncError or UnhandledAsyncError, and
* Print a detailed message similar to what's printed when a test fails.

@mkustermann

**Comment by mit-mit** [comment]
@peter-ahe-google is this still current? If so, prehaps a FixIt candidate?
