### ISSUE TITLE
Missing prerequisites in documentation

### ISSUE THREAD

**Issue by PiotrZierhoffer** [dartino/sdk#532]
To compile dartino for STM on one Ubuntu and one Mint machine I had to install one additional package, that is ```g++-multilib```.

Otherwise the commands ```ninja -C out/ReleaseIA32``` and ```ninja -C out/ReleaseSTM``` fail.

As the error message is very unclear, it would be beneficial to have it in the docs.

**Comment by sgjesse** [comment]
I have updated https://github.com/dartino/sdk/wiki/Building.
