### ISSUE TITLE
volume.dart has an unused import

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#557]
The volume.dart sample has an unused import, `dart:typed_data`, causing a warning in Atom when opening the sample:

<img width="855" alt="screen shot 2016-06-30 at 13 52 03" src="https://cloud.githubusercontent.com/assets/13644170/16487256/dfde4c64-3ec9-11e6-962a-1e86f3aabb7f.png">

**Comment by jakobr-google** [comment]
Fixed in https://github.com/dartino/sdk/commit/435ddbc7a0150dcffd7e31875e7a5a4c3fb35208
