### ISSUE TITLE
Debugging broken after latest Dart roll

### ISSUE THREAD

**Issue by jakobr-google** [dartino/sdk#588]
I get the following error when I try to debug a target using eg. 'dartino debug samples/stm32f411re-nucleo/volume.dart on tty /dev/ttyACM0':

```
* the entire message you see here (including the full stack trace below)

Relative paths for dart extensions are not supported: 'src/serial_port'
Session 'local' was terminated.

```

Looks like path resolution for external libraries was changed recently on the Dart side, and now disallows relative paths. The third party serial_port library uses `import 'dart-ext:src/serial_port';`.

**Comment by karlklose** [comment]
We need to change the location of the serial port library in the same way I
did with the other libraries in the roll.

**Comment by sgjesse** [comment]
Thanks for the info Karl. I will create a CL.
