### ISSUE TITLE
Support timing out in test.dart -rfletchc

### ISSUE THREAD

**Issue by peter-ahe-google** [dartino/sdk#83]
This CL implements timing out: https://codereview.chromium.org/1256863004.

Unfortunately, there's a bunch of problems when a test times out. In particular, it is hard to get a consistent exit code when a time out occurs.

**Comment by mit-mit** [comment]
@peter-ahe-google is this still an issue? Tagging as FixIt candidate.

**Comment by mkustermann** [comment]
I think peter has landed the timeout support in 20107997b88fdbf2ce2455948f62fc079db0a138 and 64b2e528c293a669e89d31a81a0815fdcfbd84e0. The second part, namely getting consistent exit codes is partly covered by https://github.com/dart-lang/fletch/issues/342.

**Comment by mit-mit** [comment]
Closing per above comment.
