### ISSUE TITLE
No DeclarationSite for named mixin applications

### ISSUE THREAD

**Issue by peter-ahe-google** [dartino/sdk#91]
There's no DeclarationSite for named mixin applications, and MixinApplicationElementX doesn't implement DeclarationSite.

This is really an issue in dart2js, but it only affects fletch, so I've reported it here.

@johnniwinther fyi

**Comment by mit-mit** [comment]
@johnniwinther could this be supported in dart2js? @peter-ahe-google are you working on this, or should we assign it to Johnni?

**Comment by johnniwinther** [comment]
CL for review https://codereview.chromium.org/1504763003

**Comment by mit-mit** [comment]
Closing as above CL was landed.
