### ISSUE TITLE
Errors in SharedTask objects crash hosting session

### ISSUE THREAD

**Issue by smanilov** [dartino/sdk#92]
If a `task` that is performed in a worker thread in the persistent process throws an unhandled error, the hosting session crashes. If the session is not `x-end`ed, then trying to run another task in it will freeze the client process.

Example code:

    class BadTask extends SharedTask {
        Future<int> call(CommandSender s, StreamIterator<Command> i) {
            return new Future<int>(() => throw new Error());
        }
    }

    // executing this will crash the current session
    context.performTaskInWorker(new BadTask());

Also, just returning a null Future from the call method results in similar behaviour, however in this case the client process does not report any errors, just freezes straight away:

    class BadTask extends SharedTask {
        Future<int> call(CommandSender s, StreamIterator<Command> i) {
            return null;
        }
    }

    // executing this will crash the current session
    context.performTaskInWorker(new BadTask());

**Comment by peter-ahe-google** [comment]
This is related to this TODO: https://github.com/dart-lang/fletch/blob/1cb07ac8050ccfad3148f81fb061d3bac7cdf19e/pkg/fletchc/lib/src/driver/driver_main.dart#L504

**Comment by peter-ahe-google** [comment]
FYI: for exiting the service compiler due to an error, without crashing the session, consider using throwFatalError (https://github.com/dart-lang/fletch/blob/1cb07ac8050ccfad3148f81fb061d3bac7cdf19e/pkg/fletchc/lib/src/diagnostic.dart#L150)

**Comment by smanilov** [comment]
Okay, will have it in mind, thanks!

**Comment by peter-ahe-google** [comment]
Removing accepted for now to signal that this isn't as high priority as other accepted bugs in Tools.

**Comment by mit-mit** [comment]
@peter-ahe-google is this something we can won't fix? Doesn't sound that important?

**Comment by peter-ahe-google** [comment]
It isn't super important, but it is a problem. I'm not a big fan of closing bug reports when the underlying issue isn't fixed. Is there a label we can use for this?
